Error: Some improvements
- Added CroutonError::NotFound since it's a common general error
- IStream::readExactly should fail with EndOfData, not ParseError
- Don't log a backtrace every time Error::raise is called